### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by kansoit** [RandomReaper/weewx-zabbix#5]
Hello.
I installed the extension today and weewx service fails to run due to this error. I found it in many lines in the code. I finally fixed. I don't know if it is related to python3.
```
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__: Caught unrecoverable exception:
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****  inconsistent use of tabs and spaces in indentation (zabbix.py, line 89)
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****  Traceback (most recent call last):
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 148, in main
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 81, in __init__
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****      self.loadServices(config_dict)
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 153, in loadServices
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1093, in get_object
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****      mod = __import__(module)
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****    File "/usr/share/weewx/user/zabbix.py", line 89
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****      sender_stdout = p.communicate(input=s)[0]
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****                                              ^
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****  TabError: inconsistent use of tabs and spaces in indentation
Dec 15 10:05:14 pi2weewx python3[9962]: weewx[9962] CRITICAL __main__:     ****  Exiting.
```
Thanks in advanced

**Comment by RandomReaper** [comment]
Thank you for the report, you're right, this is related to python, should be fixed in 92da2982a3cec6d11486b338ecfcbd80966820e5.
